name: Publish
on:
  release:
    types: [created]      
env:
  VERSION: ${{ github.event.release.tag_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'                

      - name: install
        run: yarn            

      - name: publish                
        run: |
          echo $VERSION
          VERSION="${VERSION//v}"
          yarn version -i $VERSION
          npm publish --access public          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Documentation
        run: yarn docs

      - name: push package.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: package.json
          commit_message: Published ${{env.VERSION}}
          # https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/46
          branch: release/v${{env.VERSION}}
