name: Publish
on:
  workflow_dispatch:
env:
  VERSION: ${{ github.event.release.tag_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'                

      - name: install
        run: yarn            

      - name: publish                
        run: |
          echo $VERSION                
          npm publish --access public          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}            
